[package]
name = "scrapile"
version = "0.1.0"
edition = "2021"

[dependencies]
ketchup = "1.1.0"
logos = "0.14"
zip = "2.1"
json = "0.12"
ariadne = "0.4"
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
